name: guardian_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^17.1.0
  google_fonts: ^6.1.0
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.3.4 # Added for code generation compatibility
  dio: ^5.9.1
  fl_chart: ^1.1.1
  file_picker: ^8.0.3
  http: ^1.6.0
  web_socket_channel: ^3.0.3
  shimmer: ^3.0.0
  intl: ^0.20.2
  dotted_border: ^3.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^2.3.4
  build_runner: ^2.4.13

flutter:
  uses-material-design: true