
name: contract_assistant
description: AI-Based Car Lease / Loan Contract Review and Negotiation Assistant.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  dio: ^5.3.0
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  file_picker: ^5.3.3
  intl: ^0.18.1
  google_fonts: ^6.1.0
  flutter_markdown: ^0.6.17
  percent_indicator: ^4.2.3
  url_launcher: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
