version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: car_contract_db
    restart: always
    environment:
      POSTGRES_DB: car_contracts_db
      POSTGRES_USER: car_user
      POSTGRES_PASSWORD: car_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
